# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to='uploads/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.UsuarioTelegram')),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='uploads/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.UsuarioTelegram')),
            ],
        ),
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.UsuarioTelegram')),
            ],
        ),
    ]
