# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20170501_0105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documento',
            new_name='Document',
        ),
        migrations.RenameModel(
            old_name='Imagem',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='Texto',
            new_name='Text',
        ),
        migrations.RenameModel(
            old_name='UsuarioTelegram',
            new_name='UserTelegram',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='documento',
            new_name='document_file',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='imagem',
            new_name='image_file',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='texto',
            new_name='text_file',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usertelegram',
            old_name='codigo',
            new_name='cod',
        ),
        migrations.RenameField(
            model_name='usertelegram',
            old_name='nome',
            new_name='name',
        ),
    ]
